version: 2.1

orbs:
    project: bigbite/project@0.0.64

jobs:
    build:
        executor:
            name: project/default
            php: '8.0'
        steps:
            - checkout
            - project/setup
            - project/composer-install
            - project/phpcs
            - project/set-node:
                  version: '16'
            - project/npm-install
            - run:
                  name: Unit Tests
                  command: |
                      wp-scripts test-unit-js
            - project/npm-build
            - project/create-build

workflows:
    workflow:
        jobs:
            - build:
                  context: bigbite
                  filters:
                      branches:
                          ignore: /^.*-built$/
