<?php
/**
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'THEMER_EDITOR_JS', 'editor.js' );
define( 'THEMER_FRONTEND_JS', 'frontend.js' );
define( 'THEMER_EDITOR_DEPENDENCIES', [] );
define( 'THEMER_FRONTEND_DEPENDENCIES', [] );
define( 'THEMER_VERSION', '1.0.0-alpha.1' );
